version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_service_api
    ports:
      - 8000:8000
    environment:
      - MYSQL_DATABASE=wallet_service
      - MYSQL_HOST=wallet_service_mysql  #add to!!
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7 
    container_name: wallet_service_mysql
    command: mysqld --user=root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wallet_service
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=wallet_service_mysql
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
